GET http://localhost:3009/vehicules

###
GET http://localhost:3000/vehicules?marque=peugeot&model[]=307&model[]=3008

###
GET http://localhost:3000/vehicules/7

###
DELETE http://localhost:3000/vehicules/2

###
POST http://localhost:3000/vehicules
Content-Type: application/json

{
    "marque": "peugeot"
}


###
PUT http://localhost:3000/vehicules/1
Content-Type: application/json

{
    "marque": "renault"
}